import { Request } from "express";
import * as t from "io-ts";

import { RequiredQueryParamMiddleware } from "@pagopa/io-functions-commons/dist/src/utils/middlewares/required_query_param";
import {
  IResponse,
  ResponseErrorFromValidationErrors
} from "@pagopa/ts-commons/lib/responses";
import { PatternString } from "@pagopa/ts-commons/lib/strings";
import { enumType, withDefault } from "@pagopa/ts-commons/lib/types";
import * as E from "fp-ts/lib/Either";
import { pipe } from "fp-ts/lib/function";

export const TOKEN_QUERY_PARAM_NAME = "token";
export const FLOW_QUERY_PARAM_NAME = "flow";
export const TOKEN_HEADER_NAME = "x-pagopa-email-validation-token";

// Tokens are generated by CreateValidationTokenActivity function inside the
// io-profile project (https://github.com/pagopa/io-auth-n-identity-domain/tree/main/apps/io-profile)
// A token is in the following format:
// [tokenId ULID] + ":" + [validatorHash crypto.randomBytes(12)]
export const TokenParam = PatternString("^[A-Za-z0-9]{26}:[A-Fa-f0-9]{24}$");
export type TokenParam = t.TypeOf<typeof TokenParam>;

export const TokenQueryParamMiddleware = RequiredQueryParamMiddleware(
  TOKEN_QUERY_PARAM_NAME,
  TokenParam
);

export const TokenHeaderParamMiddleware = async (
  request: Request
): Promise<E.Either<IResponse<"IResponseErrorValidation">, TokenParam>> =>
  pipe(
    request.headers[TOKEN_HEADER_NAME],
    TokenParam.decode,
    E.mapLeft(ResponseErrorFromValidationErrors(TokenParam))
  );

// CONFIRM -> verify token and on success redirect to confirm page
// VALIDATE -> verify token and on success update the user data and redirect to result page
export enum FlowTypeEnum {
  "CONFIRM" = "CONFIRM",
  "VALIDATE" = "VALIDATE"
}
export const FlowType = enumType<FlowTypeEnum>(FlowTypeEnum, "FlowChoice");
export type FlowType = t.TypeOf<typeof FlowType>;

// even if the query param is optional the withDefault type is covering the absence
// of the value on the URL
export const ConfirmEmailFlowQueryParamMiddleware = RequiredQueryParamMiddleware(
  FLOW_QUERY_PARAM_NAME,
  withDefault(FlowType, FlowTypeEnum.CONFIRM)
);
