import { Request } from "express";
import * as t from "io-ts";

import { RequiredBodyPayloadMiddleware } from "@pagopa/io-functions-commons/dist/src/utils/middlewares/required_body_payload";
import {
  IResponse,
  ResponseErrorFromValidationErrors
} from "@pagopa/ts-commons/lib/responses";
import { PatternString } from "@pagopa/ts-commons/lib/strings";
import * as E from "fp-ts/lib/Either";
import { pipe } from "fp-ts/lib/function";
import { ValidateProfileEmailPayload } from "../generated/definitions/external/ValidateProfileEmailPayload";

export const TOKEN_QUERY_PARAM_NAME = "token";
export const FLOW_QUERY_PARAM_NAME = "flow";
export const TOKEN_HEADER_NAME = "x-pagopa-email-validation-token";

// Tokens are generated by CreateValidationTokenActivity function inside the
// io-profile project (https://github.com/pagopa/io-auth-n-identity-domain/tree/main/apps/io-profile)
// A token is in the following format:
// [tokenId ULID] + ":" + [validatorHash crypto.randomBytes(12)]
export const TokenParam = PatternString("^[A-Za-z0-9]{26}:[A-Fa-f0-9]{24}$");
export type TokenParam = t.TypeOf<typeof TokenParam>;

export const TokenHeaderParamMiddleware = async (
  request: Request
): Promise<E.Either<IResponse<"IResponseErrorValidation">, TokenParam>> =>
  pipe(
    request.headers[TOKEN_HEADER_NAME],
    TokenParam.decode,
    E.mapLeft(ResponseErrorFromValidationErrors(TokenParam))
  );

export const ValidateProfileEmailBodyMiddleware = RequiredBodyPayloadMiddleware(
  ValidateProfileEmailPayload
);
