io-session-manager:
  # changes on this files should trigger a test run
  # because vitest parses them
  - "apps/io-session-manager/**/*.pem"
  - "apps/io-session-manager/env.example"
  ######
  - "apps/io-session-manager/**/*.ts"
  # package.json, tsconfig.json, ...
  - "apps/io-session-manager/**/*.json"
  # container edit
  - docker/io-session-manager/*
  - docker/testenv2/*
io-fast-login:
  - "apps/io-fast-login/**/*.ts"
  # package.json, function.json, tsconfig.json, ...
  - "apps/io-fast-login/**/*.json"
io-lollipop:
  - "apps/io-lollipop/**/*.ts"
  # package.json, function.json, tsconfig.json, ...
  - "apps/io-lollipop/**/*.json"
  # container edit
  - docker/functions-node-20/*
  - docker/io-lollipop/*
io-profile:
  - "apps/io-profile/**/*.ts"
  # package.json, function.json, tsconfig.json, ...
  - "apps/io-profile/**/*.json"
io-profile-async:
  - "apps/io-profile-async/**/*.ts"
  # package.json, function.json, tsconfig.json, ...
  - "apps/io-profile-async/**/*.json"
io-public:
  - "apps/io-public/**/*.ts"
  # package.json, function.json, tsconfig.json, ...
  - "apps/io-public/**/*.json"
io-session-manager-internal:
  - "apps/io-session-manager-internal/**/*.ts"
  # package.json, function.json, tsconfig.json, ...
  - "apps/io-session-manager-internal/**/*.json"
io-web-profile:
  - "apps/io-web-profile/**/*.ts"
  # package.json, function.json, tsconfig.json, ...
  - "apps/io-web-profile/**/*.json"
io-auth-n-identity-commons:
  - "packages/io-auth-n-identity-commons/**/*.ts"
  # package.json, function.json, tsconfig.json, ...
  - "packages/io-auth-n-identity-commons/**/*.json"
io-auth-n-identity-db-models:
  - "packages/io-auth-n-identity-db-models/**/*.ts"
  # package.json, function.json, tsconfig.json, ...
  - "packages/io-auth-n-identity-db-models/**/*.json"
bruno-io-lollipop:
  - "bruno/io-lollipop/**/*.json"
  - "bruno/io-lollipop/**/*.bru"
