plan-action:
  - ".github/workflows/pr_opex_api_session_manager.yaml"
  - ".github/workflows/pr_opex_api_lollipop.yaml"
  - ".github/workflows/pr_opex_api_profile.yaml"
  - ".github/workflows/pr_opex_api_public.yaml"
  - ".github/workflows/pr_opex_api_web_profile.yaml"
  - ".github/workflows/call_pr_opex_api.yml"
apply-action:
  - ".github/workflows/opex_api_session_manager.yaml"
  - ".github/workflows/opex_api_lollipop.yaml"
  - ".github/workflows/opex_api_profile.yaml"
  - ".github/workflows/opex_api_public.yaml"
  - ".github/workflows/opex_api_web_profile.yaml"
  - ".github/workflows/call_opex_api.yml"
bpd:
  - "apps/io-session-manager/api/sso/bpd.yaml"
  - "apps/io-session-manager/.opex/bpd/**"
external:
  - "apps/io-session-manager/api/external.yaml"
  - "apps/io-session-manager/.opex/external/**"
fims:
  - "apps/io-session-manager/api/sso/fims.yaml"
  - "apps/io-session-manager/.opex/fims/**"
internal:
  - "apps/io-session-manager/api/internal.yaml"
  - "apps/io-session-manager/.opex/internal/**"
pagopa:
  - "apps/io-session-manager/api/sso/pagopa.yaml"
  - "apps/io-session-manager/.opex/pagopa/**"
zendesk:
  - "apps/io-session-manager/api/sso/zendesk.yaml"
  - "apps/io-session-manager/.opex/zendesk/**"
lollipop-external:
  - "apps/io-lollipop/api/external.yaml"
  - "apps/io-lollipop/.opex/external/**"
profile-support:
  - "apps/io-profile/api/support.yaml"
  - "apps/io-profile/.opex/support/**"
public-external:
  - "apps/io-public/api/external.yaml"
  - "apps/io-public/.opex/external/**"
web-profile-external:
  - "apps/io-web-profile/api/external.yaml"
  - "apps/io-web-profile/.opex/external/**"
