plan-action:
  - ".github/workflows/pr_opex_api_session_manager.yaml"
  - ".github/workflows/pr_opex_api_lollipop.yaml"
  - ".github/workflows/pr_opex_api_web_profile.yml"
  - ".github/workflows/call_pr_opex_api.yml"
apply-action:
  - ".github/workflows/opex_api_session_manager.yaml"
  - ".github/workflows/opex_api_lollipop.yaml"
  - ".github/workflows/opex_api_web_profile.yml"
  - ".github/workflows/call_opex_api.yml"
bpd:
  - "apps/io-session-manager/api/bpd.yaml"
  - "apps/io-session-manager/.opex/bpd/**"
fast-login:
  - "apps/io-session-manager/api/fast-login.yaml"
  - "apps/io-session-manager/.opex/fast-login/**"
fims:
  - "apps/io-session-manager/api/fims.yaml"
  - "apps/io-session-manager/.opex/fims/**"
internal:
  - "apps/io-session-manager/api/internal.yaml"
  - "apps/io-session-manager/.opex/internal/**"
pagopa:
  - "apps/io-session-manager/api/pagopa.yaml"
  - "apps/io-session-manager/.opex/pagopa/**"
public:
  - "apps/io-session-manager/api/public.yaml"
  - "apps/io-session-manager/.opex/public/**"
zendesk:
  - "apps/io-session-manager/api/zendesk.yaml"
  - "apps/io-session-manager/.opex/zendesk/**"
lollipop-external:
  - "apps/io-lollipop/api/external.yaml"
  - "apps/io-lollipop/.opex/external/**"
web-profile-external:
  - "apps/io-web-profile/api/external.yaml"
  - "apps/io-web-profile/.opex/external/**"
