repos:
  - repo: https://github.com/pagopa/dx
    rev: pre_commit_scripts@0.0.1
    hooks:
      - id: lock_modules
        exclude: ^.*/(_modules|\.terraform)(/.*)?$
        # Configure the paths to your Terraform configurations
        files: infra/(github-runner|identity|modules|repository|resources)