cleanupUnusedCatalogs: false
linkWorkspacePackages: true
packageImportMethod: clone-or-copy
packages:
  - apps/*
  - bruno
  - packages/*

catalog:
  '@azure/cosmos': ^4.1.1
  '@azure/data-tables': ^13.3.2
  '@azure/functions': ^4.7.0
  '@azure/identity': ^4.10.1
  '@azure/service-bus': ^7.9.5
  '@azure/storage-blob': ^12.29.1
  '@azure/storage-queue': ^12.22.0
  '@mattrglobal/http-signatures': ^4.1.0
  '@pagopa/azure-storage-migration-kit': ^0.0.2
  '@pagopa/eslint-config': ^4.0.6
  '@pagopa/express-azure-functions': ^4.0.1
  '@pagopa/handler-kit': ^1.1.1
  '@pagopa/handler-kit-azure-func': ^2.0.8
  '@pagopa/io-app-email-templates': ^0.8.0
  '@pagopa/io-functions-commons': ^29.3.0
  '@pagopa/io-spid-commons': ^14.0.1
  '@pagopa/logger': ^1.0.1
  '@pagopa/openapi-codegen-ts': ^14.0.1
  '@pagopa/ts-commons': ^13.1.2
  '@pagopa/winston-ts': ^2.2.0
  '@redis/client': 1.6.1
  '@types/body-parser': ^1.0.0
  '@types/cookie-parser': ^1.4.8
  '@types/express': ^4.17.21
  '@types/html-to-text': ^9.0.4
  '@types/jsonwebtoken': ^9.0.2
  '@types/jwk-to-pem': ^2.0.1
  '@types/lolex': ^3.1.1
  '@types/node': ^20.19.5
  '@types/node-fetch': ^2.6.11
  '@types/nodemailer': ^6.4.17
  '@types/passport': ^1.0.3
  '@types/passport-http-bearer': ^1.0.34
  '@types/passport-local': ^1.0.38
  '@types/supertest': ^6.0.2
  '@types/vfile-message': ^2.0.0
  '@types/xml-crypto': ^1.4.2
  '@vitest/coverage-v8': ^3.2.4
  '@xmldom/xmldom': ^0.8.10
  applicationinsights: ^2.9.5
  azure-storage: ^2.10.7
  base64url: ^3.0.1
  body-parser: ^1.20.2
  cookie-parser: ^1.4.7
  date-fns: ^2.30.0
  dependency-check: ^4.1.0
  dotenv: ^16.4.5
  dotenv-cli: ^7.4.1
  durable-functions: ^2.1.4
  eslint: ^8.57.0
  eslint-plugin-prettier: ^5.1.3
  express: ^4.19.2
  fast-check: ^1.16.0
  fp-ts: ^2.16.9
  helmet: ^7.1.0
  html-to-text: ^9.0.5
  http-graceful-shutdown: ^3.1.13
  io-ts: ^2.2.22
  io-ts-types: ^0.5.19
  jose: ^5.3.0
  jsonwebtoken: ^9.0.2
  jwk-to-pem: ^2.0.5
  logform: ^2.6.0
  lolex: ^5.1.1
  mock-http-server: ^1.4.5
  modclean: ^3.0.0-beta.1
  monocle-ts: ^2.3.13
  newtype-ts: ^0.3.5
  node-fetch: ^2.6.9
  nodemailer: ^6.10.0
  oval: ^1.0.0
  passport: ^0.6.0
  passport-http-bearer: ^1.0.1
  passport-http-custom-bearer: ^1.0.15
  passport-local: ^1.0.0
  passport-strategy: ^1.0.0
  prettier: ^3.2.5
  range_check: ^2.0.4
  redis: 4.7.1
  shx: ^0.4.0
  supertest: ^7.0.0
  swagger-cli: ^4.0.4
  timekeeper: ^2.2.0
  typescript: ^5.4.5
  ulid: ^2.3.0
  vitest: ^3.2.4
  winston: ^3.14.2
  winston-transport: ^4.9.0
  xml-crypto: 2.1.6
