cleanupUnusedCatalogs: true
linkWorkspacePackages: true
packageImportMethod: clone-or-copy
packages:
  - apps/*
  - bruno
  - packages/*

catalog:
  '@azure/service-bus': ^7.9.5
  '@pagopa/logger': ^1.0.1
  monocle-ts: ^2.3.13
  newtype-ts: ^0.3.5
  ulid: ^2.3.0
  winston-transport: ^4.9.0
  '@pagopa/eslint-config': ^4.0.6
  '@vitest/coverage-v8': ~3.2.4
  dependency-check: ^4.1.0
  eslint: ^8.57.0
  eslint-plugin-prettier: ^5.1.3
  modclean: ^3.0.0-beta.1
  prettier: ^3.2.5
  swagger-cli: ^4.0.4
  vitest: ~3.2.4
