import { EmailAddress } from "@pagopa/hexagonal-core";
import { z } from "zod";
import {
  getRandomBytesHex,
  Sha256HexStringSchema,
  toSha256,
} from "../../../utils/hash.js";
import { PlainSessionToken } from "./session-token.vo.js";

const SHA256_HEX_LENGTH = 64;
const EXTENDED_ZENDESK_SSO_TOKEN_SUFFIX_BYTES_LENGTH = 4;
const EXTENDED_ZENDESK_SSO_TOKEN_SUFFIX_HEX_LENGTH =
  EXTENDED_ZENDESK_SSO_TOKEN_SUFFIX_BYTES_LENGTH * 2;
const EXTENDED_ZENDESK_SSO_TOKEN_HEX_LENGTH =
  SHA256_HEX_LENGTH + EXTENDED_ZENDESK_SSO_TOKEN_SUFFIX_HEX_LENGTH;

// ------------------------------------------------------------------------------
// Plain Zendesk SSO Token Value Object
// ------------------------------------------------------------------------------

export declare const _plainZendeskSSOTokenBrand: unique symbol;

// Zod schemas with string literal brands
export const PlainZendeskSSOTokenSchema =
  Sha256HexStringSchema.brand<typeof _plainZendeskSSOTokenBrand>();

export type PlainZendeskSSOToken = z.infer<typeof PlainZendeskSSOTokenSchema>;

// ------------------------------------------------------------------------------
// Extended Plain Zendesk SSO Token Value Object
// ------------------------------------------------------------------------------

export declare const _extendedPlainZendeskSSOTokenBrand: unique symbol;

// Zod schemas with string literal brands
export const ExtendedPlainZendeskSSOTokenSchema = z
  .string()
  .regex(new RegExp(`^[a-fA-F0-9]{${EXTENDED_ZENDESK_SSO_TOKEN_HEX_LENGTH}}$`)) // Matches a 72-character hexadecimal string (64 characters for the SHA-256 hash and 8 characters for the suffix)
  .brand<typeof _extendedPlainZendeskSSOTokenBrand>();

export type ExtendedPlainZendeskSSOToken = z.infer<
  typeof ExtendedPlainZendeskSSOTokenSchema
>;

// ------------------------------------------------------------------------------
// Hashed Zendesk SSO Token Value Object
// ------------------------------------------------------------------------------

export declare const _hashedZendeskSSOTokenBrand: unique symbol;

export const HashedZendeskSSOTokenSchema =
  Sha256HexStringSchema.brand<typeof _hashedZendeskSSOTokenBrand>();

export type HashedZendeskSSOToken = z.infer<typeof HashedZendeskSSOTokenSchema>;

// ------------------------------------------------------------------------------
// Helper functions
// ------------------------------------------------------------------------------

export const toPlainZendeskSSOToken = (
  token: PlainSessionToken,
): PlainZendeskSSOToken =>
  PlainZendeskSSOTokenSchema.parse(toSha256(`zendesk:${token}`));

export const toPlainZendeskSSOTokenFromExtended = (
  token: ExtendedPlainZendeskSSOToken,
): PlainZendeskSSOToken =>
  PlainZendeskSSOTokenSchema.parse(token.substring(0, SHA256_HEX_LENGTH));

/**
 * Extends a plain session token to create an extended plain Zendesk SSO token.
 * The extended token is generated by appending a suffix to the SHA-256 hash of the session token.
 * The suffix is either derived from the provided email address (if available) or generated randomly.
 * @param token The plain session token
 * @param email The email address to be used for generating the suffix (optional)
 * @returns The extended plain Zendesk SSO token
 */
export const toExtendedPlainZendeskSSOToken = async (
  token: PlainSessionToken,
  email?: EmailAddress,
): Promise<ExtendedPlainZendeskSSOToken> => {
  const suffix = email
    ? toSha256(email).substring(0, EXTENDED_ZENDESK_SSO_TOKEN_SUFFIX_HEX_LENGTH)
    : await getRandomBytesHex(EXTENDED_ZENDESK_SSO_TOKEN_SUFFIX_BYTES_LENGTH);
  return ExtendedPlainZendeskSSOTokenSchema.parse(
    `${toPlainZendeskSSOToken(token)}${suffix}`,
  );
};

export const toHashedZendeskSSOToken = (
  plainToken: PlainZendeskSSOToken,
): HashedZendeskSSOToken =>
  HashedZendeskSSOTokenSchema.parse(toSha256(plainToken));
