openapi: 3.0.1
info:
  version: 0.1.0
  title: IO Session Manager Internal API
  x-logo:
    url: https://io.italia.it/assets/img/io-logo-blue.svg
  description: |
    Documentation of the IO Session Manager Internal API here.
servers:
  - url: https://io-p-weu-auth-sm-int-func-01.azurewebsites.net/api/v1
paths:
  /info:
    get:
      operationId: info
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApplicationInfo"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
  /sessions/{fiscalcode}:
    get:
      operationId: getSession
      summary: Get available user info from session
      description: |-
        Use this operation if you want to known the state of user session
      parameters:
        - $ref: "#/components/parameters/FiscalCode"
      responses:
        "200":
          description: Success.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserSessionInfo"
              example:
                "active": true
        "400":
          description: Bad request
        "401":
          description: Token null or invalid.
        "404":
          description: User not found.
        "429":
          description: Throttling.
        "500":
          description: There was an error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemJson"
components:
  parameters:
    FiscalCode:
      name: fiscalcode
      in: path
      required: true
      description: The fiscal code of the user, all in upper case.
      schema:
        type: string
        maxLength: 16
        minLength: 16
        pattern: >-
          [A-Z]{6}[0-9LMNPQRSTUV]{2}[ABCDEHLMPRST][0-9LMNPQRSTUV]{2}[A-Z][0-9LMNPQRSTUV]{3}[A-Z]
        x-example: SPNDNL80R13C555X
  schemas:
    ApplicationInfo:
      type: object
      properties:
        name:
          type: string
          example: io-session-manager-internal
        version:
          type: string
          example: 1.0.0
      required:
        - name
        - version
    ProblemJson:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/v28.22.0/openapi/definitions.yaml#/ProblemJson"
    UserSessionInfo:
      type: object
      properties:
        active:
          type: boolean
      required:
        - active
