oa3_spec: apps/io-lollipop/api/external.yaml
name: opex_io_lollipop_api_external
location: Italy North
timespan: 10m
resource_type: api-management
data_source: /subscriptions/ec285037-c673-4f58-b594-d7c480da4e8b/resourceGroups/io-p-rg-external/providers/Microsoft.Network/applicationGateways/io-p-appgateway
action_groups:
  - /subscriptions/EC285037-C673-4F58-B594-D7C480DA4E8B/resourceGroups/io-p-rg-common/providers/microsoft.insights/actionGroups/iopquarantineerror
overrides:
  hosts:
    - api.io.pagopa.it
    - api.io.italia.it
    - api-app.internal.io.pagopa.it
