import { readFile, writeFile } from "node:fs/promises";

const generatedTypesPath = new URL(
  "../src/generated/io-lollipop/types.gen.ts",
  import.meta.url,
);
const source = await readFile(generatedTypesPath, "utf8");
const target = "export type JwkPubKey = string;";

if (!source.includes(target)) {
  throw new Error("Unable to patch the generated JwkPubKey type");
}

const patched = source
  .replace(
    "// This file is auto-generated by @hey-api/openapi-ts\n",
    '// This file is auto-generated by @hey-api/openapi-ts\n\nimport type { JwkPublicKey } from "@pagopa/io-auth-n-identity-domain";\n',
  )
  .replace(target, "export type JwkPubKey = JwkPublicKey;");

await writeFile(generatedTypesPath, patched);
