swagger: "2.0"
info:
  version: 1.0.0
  title: Public API
  description: Mobile and web proxy API gateway.
host: localhost
basePath: /
schemes:
  - https
paths:
  "/login":
    get:
      operationId: login
      summary: Login SPID/CIE
      description: Login with SPID or CIE for IO APP
      parameters:
        - $ref: "#/parameters/EntityId"
        - $ref: "#/parameters/AuthLevel"
        - $ref: "#/parameters/JwkPubKeyToken"
        - $ref: "#/parameters/JwkPubKeyHashAlgorithm"
        - $ref: "#/parameters/LoginType"
      responses:
        "302":
          description: Redirect to IDP
          headers:
            Location:
              type: string
              description: Redirect endpoint with SAML AuthNRequest query parameters
        "400":
          description: Bad Request
          schema:
            $ref: "#/definitions/ProblemJson"
        "500":
          description: Internal Server Error
          schema:
            $ref: "#/definitions/ProblemJson"
        "503":
          description: Service unavailable
  "/test-login":
    post:
      operationId: testLogin
      summary: Login Test User with password
      description: Login Test User with password and Fiscal Code
      parameters:
        - in: body
          name: body
          schema:
            $ref: "#/definitions/PasswordLogin"
          required: true
          x-examples:
            application/json:
              username: AAABBB01C02D345Z
              password: secret
        - $ref: "#/parameters/JwkPubKeyToken"
        - $ref: "#/parameters/JwkPubKeyHashAlgorithm"
        - $ref: "#/parameters/LoginType"
      responses:
        "200":
          description: Access token
          schema:
            $ref: "#/definitions/AccessToken"
        "401":
          description: Invalid credentials
        "500":
          description: Unavailable service
          schema:
            $ref: "#/definitions/ProblemJson"
  "/healthcheck":
    get:
      operationId: healthcheck
      summary: The healthcheck endpoint
      description: Responde with the app version if running
      responses:
        "200":
          description: Access token
          schema:
            $ref: "#/definitions/BackendVersion"
  "/assertionConsumerService":
    post:
      operationId: acs
      summary: ACS step of Login SPID/CIE
      description: Login with SPID or CIE for IO APP
      parameters:
        - in: body
          name: body
          schema:
            $ref: "#/definitions/SAMLResponse"
      responses:
        "301":
          description: Redirect to home page
          headers:
            Location:
              type: string
definitions:
  FiscalCode:
    $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/v28.18.3/openapi/definitions.yaml#/FiscalCode"
  ProblemJson:
    $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/v28.18.3/openapi/definitions.yaml#/ProblemJson"
  BackendVersion:
    type: object
    title: The App version
    properties:
      version:
        type: string
  ServerInfo:
    type: object
    title: Server information
    properties:
      version:
        type: string
      min_app_version:
        $ref: "#/definitions/VersionPerPlatform"
      min_app_version_pagopa:
        $ref: "#/definitions/VersionPerPlatform"
    required:
      - version
      - min_app_version
      - min_app_version_pagopa
  VersionPerPlatform:
    type: object
    title: Specify a version for ios and another for android
    properties:
      ios:
        type: string
      android:
        type: string
    required:
      - ios
      - android
  PasswordLogin:
    type: object
    properties:
      username:
        $ref: "#/definitions/FiscalCode"
      password:
        type: string
        minLength: 1
    required:
      - username
      - password
  AccessToken:
    type: object
    properties:
      token:
        type: string
        minLength: 1
    required:
      - token
  SAMLResponse:
    type: string
    description: A string representation of a signed SPID/CIE response
    minLength: 1
consumes:
  - application/json
produces:
  - application/json
parameters:
  EntityId:
    name: entityID
    in: query
    type: string
    enum:
      - lepidaid
      - infocertid
      - sielteid
      - namirialid
      - timid
      - arubaid
      - posteid
      - spiditalia
      - teamsystemid
      - ehtid
      - infocamereid
      - intesiid
      - xx_servizicie_coll
      - xx_servizicie
      - xx_servizicie_test
    description: An ID that refers to a specific IDP
    required: true
  AuthLevel:
    name: authLevel
    in: query
    type: string
    enum: [SpidL2, SpidL3]
    description: SPID AuthLevel
    required: true
    x-example: SpidL2
  LoginType:
    name: loginType
    in: header
    type: string
    enum: [LV, LEGACY]
    required: false
    x-example: LEGACY
  JwkPubKeyToken:
    in: header
    name: x-pagopa-lollipop-pub-key
    type: string
    description: represents a Base64url encode of a JWK Public Key
    format: JwkPublicKeyFromToken
    x-import: "@pagopa/ts-commons/lib/jwk"
    x-example: "eyJrdHkiOiJFQyIsImNydiI6IlAtMjU2IiwieCI6IjRmMzB6dUdNcm9kRXl3cEoxelZKbWFRLVYtZlM4OVZBTW8yZnN6dWxOTmsiLCJ5IjoibG5NdmExengxaFJncVY5enVEU3dkV0dyUlhTREl4UXQ1YVJVeG1EVW44NCJ9"
  JwkPubKeyHashAlgorithm:
    in: header
    name: x-pagopa-lollipop-pub-key-hash-algo
    type: string
    enum: [sha256, sha384, sha512]
    description: Represents the selected hashing algorithm for jwk thumbprint
    x-example: "sha256"
