openapi: 3.0.1
info:
  version: 1.0.1
  title: IO Fast Login Function API
  x-logo:
    url: https://io.italia.it/assets/img/io-logo-blue.svg
  description: |
    Documentation of the IO Fast Login Function API here.
servers:
  - url: https://io-p-weu-fast-login-fn.azurewebsites.net/api/v1
security:
  - ApiKeyAuth: []
paths:
  /info:
    get:
      operationId: info
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationInfo'
        '404':
          description: Not Found
        '500':
          description: Internal Server error
  /fast-login:
    post:
      operationId: fastLogin
      parameters:
        - name: x-pagopa-lollipop-original-method
          in: header
          description: The method of the endpoint called by IO app
          required: true
          schema:
            $ref: '#/components/schemas/LollipopMethod'
        - name: x-pagopa-lollipop-original-url
          in: header
          description: The url of the endpoint called by IO app
          required: true
          schema:
            $ref: '#/components/schemas/LollipopOriginalURL'
        - name: x-pagopa-lollipop-auth-jwt
          in: header
          description: Auth token to retrieve the SPID/CIE User identity from IO
          required: true
          schema:
            $ref: '#/components/schemas/LollipopJWTAuthorization'
        - name: x-pagopa-lollipop-assertion-ref
          in: header
          description: The id of the assertion to retrieve
          required: true
          schema:
            $ref: '#/components/schemas/LollipopAssertionRef'
        - name: x-pagopa-lollipop-assertion-type
          in: header
          description: The assertion type (SAML / OIDC)
          required: true
          schema:
            $ref: '#/components/schemas/AssertionType'
        - name: x-pagopa-lollipop-user-id
          in: header
          description: User's fiscal code.
          required: true
          schema:
            $ref: '#/components/schemas/LollipopUserId'
        - name: x-pagopa-lollipop-public-key
          in: header
          description: User's public key
          required: true
          schema:
            $ref: '#/components/schemas/LollipopPublicKey'
        - name: signature-input
          in: header
          description: The signature input, needed to verify the `signature` header
          required: true
          schema:
            $ref: '#/components/schemas/LollipopSignatureInput'
        - name: signature
          in: header
          description: >-
            The signature of the HTTP request, signed by the client with its
            private key.
          required: true
          schema:
            $ref: '#/components/schemas/LollipopSignature'
        - name: x-pagopa-fast-login-refresh-type
          in: header
          description: The source of the fast-login request
          required: true
          schema:
            $ref: '#/components/schemas/FastLoginRequestType'
      responses:
        '200':
          description: Success response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FastLoginResponse'
        '401':
          description: Unauthorized
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-Functions-Key
  schemas:
    ApplicationInfo:
      type: object
      properties:
        message:
          type: string
      required:
        - message
    FastLoginResponse:
      type: object
      properties:
        SAMLResponse:
          type: string
          minLength: 1
      required:
        - SAMLResponse
    ProblemJson:
      type: object
      properties:
        type:
          type: string
          format: uri
          description: |-
            An absolute URI that identifies the problem type. When dereferenced,
            it SHOULD provide human-readable documentation for the problem type
            (e.g., using HTML).
          default: about:blank
          example: https://example.com/problem/constraint-violation
        title:
          type: string
          description: >-
            A short, summary of the problem type. Written in english and
            readable

            for engineers (usually not suited for non technical stakeholders and

            not localized); example: Service Unavailable
        status:
          type: integer
          format: int32
          description: >-
            The HTTP status code generated by the origin server for this
            occurrence

            of the problem.
          minimum: 100
          maximum: 600
          exclusiveMaximum: true
          example: 200
        detail:
          type: string
          description: |-
            A human readable explanation specific to this occurrence of the
            problem.
          example: There was an error processing the request
        instance:
          type: string
          format: uri
          description: >-
            An absolute URI that identifies the specific occurrence of the
            problem.

            It may or may not yield further information if dereferenced.
    LollipopMethod:
      type: string
      enum:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
    LollipopOriginalURL:
      type: string
      pattern: ^https://
    AssertionType:
      type: string
      enum:
        - SAML
        - OIDC
    LollipopAssertionRef:
      oneOf:
        - type: string
          pattern: ^(sha256-[A-Za-z0-9-_=]{1,44})$
        - type: string
          pattern: ^(sha384-[A-Za-z0-9-_=]{1,66})$
        - type: string
          pattern: ^(sha512-[A-Za-z0-9-_=]{1,88})$
    LollipopUserId:
      type: string
      description: User's fiscal code.
      format: FiscalCode
      x-import: '@pagopa/ts-commons/lib/strings'
      example: SPNDNL80R13C555X
    LollipopPublicKey:
      type: string
      minLength: 1
      description: represents a Base64url encode of a JWK Public Key
    LollipopJWTAuthorization:
      type: string
      minLength: 1
    LollipopSignatureInput:
      type: string
      pattern: ^(((sig[0-9]+)=[^,]*?)(, ?)?)+$
    LollipopSignature:
      type: string
      pattern: ^((sig[0-9]+)=:[A-Za-z0-9+/=]*:(, ?)?)+$
    FastLoginRequestType:
      type: string
      enum:
        - BIOMETRIC
        - SILENT
