name: Deploy (io-fast-login)

on:
  workflow_dispatch:

env:
  FAST_LOGIN_RESOURCE_GROUP: io-p-itn-auth-lv-rg-01
  FAST_LOGIN_APP_NAME: io-p-itn-auth-lv-func-02

jobs:
  deploy_to_azure:
    name: Deploy to Azure Function App
    uses: pagopa/dx/.github/workflows/function_app_deploy.yaml@add-healthcheck-and-optional-swap
    with:
      # '-cd' suffix added inside the pipeline
      environment: apps-prod
      resource_group_name: ${{ env.FAST_LOGIN_RESOURCE_GROUP }}
      workspace_name: "io-fast-login"
      function_app_name: ${{ env.FAST_LOGIN_APP_NAME }}
      health_check_path: "/info"
      use_staging_slot: true
      use_private_agent: true
    secrets: inherit
