name: Deploy (io-web-profile)

on:
  workflow_dispatch:

jobs:
  deploy_to_azure:
    name: Deploy to Azure Function App
    uses: pagopa/dx/.github/workflows/function_app_deploy.yaml@86ef40ee9f04895853c191b9d2ea894dade1a972
    with:
      # '-cd' suffix added inside the pipeline
      environment: app-prod
      resource_group_name: "io-p-itn-auth-webprof-rg-01"
      workspace_name: "io-web-profile"
      function_app_name: "io-p-itn-auth-webprof-func-01"
      use_staging_slot: true
      use_private_agent: true
    secrets: inherit
