name: Deploy (io-fast-login)

on:
  workflow_dispatch:

jobs:
  # this job is needed because in a reusable workflow like the one below
  # the environment can't be set. therefore, because the env vars needed are
  # only available to a specific environment we need a workaround to pass them
  prepare_envs:
    runs-on: ubuntu-22.04
    environment: apps-prod-cd
    outputs:
      resource_group_name: ${{ vars.FAST_LOGIN_RESOURCE_GROUP }}
      function_app_name: ${{ vars.FAST_LOGIN_APP_NAME }}
    steps:
      - name: dummy
        run: exit 0
        shell: bash

  deploy_to_azure:
    name: Deploy to Azure Function App
    needs: prepare_envs
    uses: pagopa/dx/.github/workflows/function_app_deploy.yaml@add-healthcheck-and-optional-swap
    with:
      # '-cd' suffix added inside the pipeline
      environment: apps-prod
      resource_group_name: ${{ needs.prepare_envs.outputs.resource_group_name }}
      workspace_name: "io-fast-login"
      function_app_name: ${{ needs.prepare_envs.outputs.function_app_name }}
      health_check_path: "/info"
      use_staging_slot: true
      use_private_agent: true
    secrets: inherit
