name: Drift Detection

on:
  workflow_dispatch:
  schedule:
    - cron: "00 06 * * *" # Run at 06:00 (UTC) every day

jobs:
  drift_detection:
    uses: pagopa/dx/.github/workflows/infra_drift_detection.yml@723b8233cd9c48bac7cc9e796471d4e12d4f8e5c # main
    name: Drift Detection
    secrets: inherit
    with:
      environment: prod
      base_path: "infra/resources/"
      override_github_environment: "infra-prod"
      use_private_agent: true
