name: Drift Detection

on:
  workflow_dispatch:
  schedule:
    - cron: "00 06 * * *" # Run at 06:00 (UTC) every day

jobs:
  drift_detection:
    uses: pagopa/dx/.github/workflows/infra_drift_detection.yml@625f02f382c33eb449cd94facb8e426bf7ae37ea # main
    name: Drift Detection
    secrets: inherit
    with:
      environment: prod
      base_path: "infra/resources/"
      override_github_environment: "infra-prod"
      use_private_agent: true
