name: Drift Detection

on:
  workflow_dispatch:
  schedule:
    - cron: "00 06 * * *" # Run at 06:00 (UTC) every day

jobs:
  drift_detection:
    uses: pagopa/dx/.github/workflows/infra_drift_detection.yml@8ec64257f46bb8c03509d317b42fbf6a2da2c63a # main
    name: Drift Detection
    secrets: inherit
    with:
      environment: prod
      base_path: "infra/resources/"
      override_github_environment: "infra-prod"
      use_private_agent: true
