name: Opex Dashboard api_zendesk

on:
  push:
    branches:
      - main
    paths:
      - "apps/session-manager/api/zendesk.yaml"
      - ".github/workflows/opex_api_zendesk.yml"
      - ".opex/zendesk/**"

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}

jobs:
  apply:
    uses: ./.github/workflows/call_opex_api.yml
    name: Apply changes to Production
    secrets: inherit
    with:
      api_name: zendesk
