name: Opex Dashboard Web Profile

on:
  push:
    branches:
      - main
    paths:
      - "apps/io-web-profile/api/*.yaml"
      - ".github/workflows/opex_api_web_profile.yaml"
      - ".github/workflows/call_opex_api.yml"
      - "apps/io-web-profile/.opex/**"

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}

jobs:
  filter:
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: read
    outputs:
      apply-action: ${{ steps.filter.outputs.apply-action }}
      web-profile-external: ${{ steps.filter.outputs.web-profile-external }}
    # Checks to see if openapi specs in the PR match one of the ones listed.
    # We can use the result to decide which job to run
    # With this type of filter we can avoid creating a lot of workflow files
    steps:
      # path-filters action requires checkout with push event
      - uses: actions/checkout@v4
        with:
          fetch-depth: 20
      - uses: dorny/paths-filter@v3.0.2
        id: filter
        with:
          filters: ./.github/opex_filters.yaml

  apply-web-profile-external:
    needs: filter
    if: ${{ needs.filter.outputs.web-profile-external == 'true' || needs.filter.outputs.apply-action == 'true' }}
    uses: ./.github/workflows/call_opex_api.yml
    name: (Web Profile - External) Apply changes to Production
    secrets: inherit
    with:
      api_name: external
      app_name: io-web-profile
