name: Opex Dashboard bpd

on:
  push:
    branches:
      - main
    paths:
      - "apps/session-manager/api/bpd.yaml"
      - ".github/workflows/opex_api_bpd.yaml"
      - ".opex/bpd/**"

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}

jobs:
  apply:
    uses: ./.github/workflows/call_opex_api.yml
    name: Apply changes to Production
    secrets: inherit
    with:
      api_name: bpd
