name: Opex Dashboard Pagopa

on:
  push:
    branches:
      - main
    paths:
      - "apps/session-manager/api/pagopa.yaml"
      - ".github/workflows/opex_api_pagopa.yaml"
      - ".opex/pagopa/**"

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}

jobs:
  apply:
    uses: ./.github/workflows/call_opex_api.yml
    name: Apply changes to Production
    secrets: inherit
    with:
      api_name: pagopa
