name: PR Infrastructure Plan

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - "infra/resources/**"
      - ".github/workflows/**_infra.yaml"
      # Terraform version edit
      - ".terraform-version"

jobs:
  code_review_prod:
    uses: pagopa/dx/.github/workflows/infra_plan.yaml@0a16d016ec102ac7a8b8f419bdb1f946c7f581f3
    name: Code Review Infrastructure Plan
    secrets: inherit
    with:
      environment: prod
      base_path: infra/resources
      override_github_environment: "infra-prod"
      use_private_agent: true
