name: Release Infrastructure

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "infra/resources/**"
      # Terraform version edit
      - ".terraform-version"

jobs:
  release_prod:
    uses: pagopa/dx/.github/workflows/infra_apply.yaml@a08a2c9d95678902fd74382804693d33c8169e55
    name: Release Infrastructure
    secrets: inherit
    with:
      environment: prod
      base_path: infra/resources
      override_github_environment: "infra-prod"
      use_private_agent: true
