name: Release Infrastructure

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "infra/resources/**"
      # Terraform version edit
      - ".terraform-version"

jobs:
  release_prod:
    uses: pagopa/dx/.github/workflows/infra_apply.yaml@b9adace755279dd84b43d0f3281525e88aa563d7
    name: Release Infrastructure
    secrets: inherit
    with:
      environment: prod
      base_path: infra/resources
      override_github_environment: "infra-prod"
      use_private_agent: true
