name: Terraform Validation

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
    paths:
      - infra/**
      - .terraform-version
      - .pre-commit-config.yaml
      - .trivyignore

jobs:
  tf_analysis:
    # Don't run in Changeset PRs
    if: ${{ github.actor != 'dx-pagopa-bot' }}
    uses: pagopa/dx/.github/workflows/static_analysis.yaml@main
    name: Terraform Validation
    secrets: inherit
    with:
      enable_modified_files_detection: true
      pre_commit_tf_tag: v1.97.3@sha256:cab76405fc6d068e20ca7c5a6f8d17c527356eed31dbc54151aec9fac65da128
