name: Terraform Validation

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
    paths:
      - infra/**
      - .terraform-version
      - .pre-commit-config.yaml
      - .trivyignore

jobs:
  tf_analysis:
    # Don't run in Changeset PRs
    if: ${{ github.actor != 'github-actions[bot]' }}
    uses: pagopa/dx/.github/workflows/static_analysis.yaml@3585afcf2d306da91d68cabfd0344a82e1ee10f3
    name: Terraform Validation
    secrets: inherit
    with:
      enable_modified_files_detection: true
